# Generated by Django 5.2.4 on 2025-07-24 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categoria",
            field=models.ForeignKey(
                default="Sin categoria",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="post.categoria",
            ),
        ),
    ]
